package com.harshitha.freelancemanager.service;

import com.lowagie.text.*;
import com.lowagie.text.pdf.*;

import org.springframework.stereotype.Service;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;

@Service
public class PdfService {

    public ByteArrayInputStream generateInvoicePdf(
            String invoiceNumber,
            Long clientId,
            Long proposalId,
            Double amount,
            String status,
            String issueDate,
            String dueDate
    ) {

        Document document = new Document();

        ByteArrayOutputStream out = new ByteArrayOutputStream();

        try {

            PdfWriter.getInstance(document, out);

            document.open();

            Font titleFont = FontFactory.getFont(
                    FontFactory.HELVETICA_BOLD,
                    20
            );

            Font headingFont = FontFactory.getFont(
                    FontFactory.HELVETICA_BOLD,
                    14
            );

            Font bodyFont = FontFactory.getFont(
                    FontFactory.HELVETICA,
                    12
            );

            Paragraph title =
                    new Paragraph("FREELANCE MANAGER", titleFont);

            title.setAlignment(Element.ALIGN_CENTER);

            document.add(title);

            document.add(new Paragraph(" "));

            document.add(new Paragraph(
                    "Invoice Number : " + invoiceNumber,
                    headingFont));

            document.add(new Paragraph(
                    "Issue Date : " + issueDate,
                    bodyFont));

            document.add(new Paragraph(
                    "Due Date : " + dueDate,
                    bodyFont));

            document.add(new Paragraph(" "));

            PdfPTable table = new PdfPTable(2);

            table.setWidthPercentage(100);

            table.addCell("Client ID");
            table.addCell(String.valueOf(clientId));

            table.addCell("Proposal ID");
            table.addCell(String.valueOf(proposalId));

            table.addCell("Amount");
            table.addCell("₹ " + amount);

            table.addCell("Status");
            table.addCell(status);

            document.add(table);

            document.add(new Paragraph(" "));

            Paragraph footer =
                    new Paragraph(
                            "Generated by Freelance Manager",
                            bodyFont);

            footer.setAlignment(Element.ALIGN_CENTER);

            document.add(footer);

            document.close();

        } catch (Exception e) {
            e.printStackTrace();
        }

        return new ByteArrayInputStream(out.toByteArray());
    }
}